# Generated by Django 5.1.7 on 2025-03-29 02:56

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "to do": "An issue for which work has not yet begun",
        "in progress": "An issue currently being worked on",
        "done": "An issue for which work has been completed"
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()
        
def populate_priority(apps, schemaeditor):
    entries = {
        "low": "Represents a low priority or severity level.",
        "medium": "Represents a moderate priority or severity level.",
        "high": "Represents a high priority or severity level."
    }
    Priority = apps.get_model("issues", "Priority")
    for key, value in entries.items():
        priority_obj = Priority(name=key, description=value)
        priority_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(populate_priority),
    ]